### PR TITLE
peter-pham-sorting

### PR DESCRIPTION
**Pull request by phamhere**

### CODE REVIEW

**Review by BrianARuff — COMMENTED** [review]
excellent job so far!

**Review by BrianARuff — APPROVED** [review]
I love you quicksort implementation. I found it very easy to follow through with esp using python tutor compared to a lot of other quicksort implementations that I have seen that still use the high, low pattern and recursion! I'd grade u at 100% if I could, great job!

**Review by BrianARuff — COMMENTED** [review]
Peter, your insertion sort showed some problems when I tested it, and I came up with a solution that will fix it, but rather than give it to you (unless you truly want it), I figured I'd let you know about the error first. I won't say specifically what is wrong but check into line 23 inside the range condition and play around with it, and see what you'll get using this array `[1, 5, 8, -6, -12, 100, 33]`

**Comment by phamhere** [comment]
Thanks for the feedback Brian! I made the changes to insertion_sort to make it work with the array that you provided. It now changes the value of 'i' after the swap to reflect the new position of the element that needs to be compared. I should have more thoroughly checked my code through tests, I apologize for that.

**Comment by BrianARuff** [comment]
Excellent job with the fix Peter!

**Pull request merged**
